### ISSUE TITLE
Missing git_info.hpp

### ISSUE THREAD

**Issue by Blazewardog** [System64fumo/syspower#2]
Doesn't currently build due to missing git_info.hpp in the repo. Looks like it is used for saving off some git commit hash/message?

**Comment by System64fumo** [comment]
git_info.hpp gets generated dynamically when compiling.
Not sure how you got it to be missing?
Check if the .git dir exists in the repo when you cloned it,
You can either create it manually by repeating the commands in the makefile or just create an empty file called git_info.hpp it's not critical.

**Comment by System64fumo** [comment]
@Blazewardog I think it's fixed, Let me know.

**Comment by Blazewardog** [comment]
Yes, that seems to have fixed it. Thanks for getting this solved quickly, the project looks neat.

**Comment by System64fumo** [comment]
"Quickly" i'm like a day late.. *whoops*

That being said thank you for actually reporting this issue, Have a good one!
