### ISSUE TITLE
undefined symbol: syspower_show_windows

### ISSUE THREAD

**Issue by 413x1nkp** [System64fumo/syspower#3]
Installed via the AUR, `syspower`
On launch prints those warnings:
```sh
Unable to open file: /home/alex/.config/sys64/power/config.conf
Cannot load symbols: /usr/lib/libsyspower.so: undefined symbol: syspower_show_windows
```

Compilation was successful, however.

**Comment by System64fumo** [comment]
Oh whoops, forgot to clean that up
My bad!

**Comment by 413x1nkp** [comment]
> Oh whoops, forgot to clean that up My bad!

It's all good, don't worry about it!
We all make mistakes :)

**Comment by System64fumo** [comment]
Fixed, can you test now?

**Comment by 413x1nkp** [comment]
> Fixed, can you test now?

Yep, works now!
Don't forget to increment the `pkgrel` var in the PKGBUILD!

**Comment by System64fumo** [comment]
Awesome!
As for the aur pkgbuild
I never increment those

I might add the commit date to them like some packages do though (Automatically grab commit date on build)
