### ISSUE TITLE
Failed to open display, what am I doing wrong? 

### ISSUE THREAD

**Issue by LoneWolf4713** [System64fumo/syspower#4]
hey, so I did make install on syspower but without sudo it can't find libsyspower.so and with sudo it can't open a display
![image](https://github.com/user-attachments/assets/b1d554ca-c1f5-4a92-b566-1b668338cea6)

what am I doing wrong? 
I'm on Arch Linux
with Hyprland 0.43.0-1

**Comment by System64fumo** [comment]
Try re-logging in
Or spawn another terminal instance
Or LD_LIBRARY_PATH=/usr/local/lib syspower

**Comment by LoneWolf4713** [comment]
hey, the LD_LIBRARY_PATH works and opens the menu but then again, on proceeding with any command, shutdown, reboot or logout, nothing really happens, it just closes the terminal in which I started syspower. that's it.

**Comment by System64fumo** [comment]
You have to detach the program so `syspower & detach` or bind it to a key in hyprland
syspower closes all programs on shutdown/reboot/whatever so when it closes the terminal that it was started from it also closes itself
Not really a bug more of a user error sorta thing, I could probably add a check for it to not kill the process it was started from but ehh...

**Comment by LoneWolf4713** [comment]
yes man that works! thanks.
