### ISSUE TITLE
Checking for existence of systemctl doesn't work on NixOS

### ISSUE THREAD

**Issue by justDeeevin** [System64fumo/syspower#9]
Presently, syspower uses `loginctl` instead of `systemctl` if it finds that `/bin/systemctl` does not exist. However, despite using systemd, nixos does not place `systemctl` in `/bin`, so syspower attempts to use `loginctl` to no avail. This ends up hanging the program and forcing the user to either use the power button on their computer or enter a TTY to kill syspower.

We should find a more reliable way to check for systemd/elogind.

**Comment by justDeeevin** [comment]
Honestly i wasn't previously aware of any scenario where `systemctl` _wasn't_ available under linux. Thus I have no idea how I would test for this.

**Comment by System64fumo** [comment]
Humm i suppose a better system can be put in place for checking that..

I don't use nix os so i don't know but does the path for systemctl exist in $PATH?
I can change the check code to check where the file exists from $PATH.

Alternatively, The better solution is to let the end user customize each button's action from the config.
But that's for later.

**Comment by System64fumo** [comment]
@justDeeevin Should be good now could you check to make sure?

**Comment by justDeeevin** [comment]
Works like a charm! :D
